### ISSUE TITLE
Consider submitting to GNU ELPA

### ISSUE THREAD

**Issue by skangas** [alexmurray/apparmor-mode#1]
Hi there,

I ran into your package while looking for Emacs syntax highlighting of apparmor profiles.

Please consider submitting this package to GNU ELPA. This requires copyright assignment to the FSF, but would allow more users to easily use your package.

Thanks!

**Comment by alexmurray** [comment]
I plan to submit it to MELPA for now, I haven't submitted to ELPA before and haven't signed FSF copyright assignment yet either so  unless there is a real compelling reason to prefer ELPA over MELPA, I think I will stick with the former since I already have a bunch of other packages there.

**Comment by skangas** [comment]
The two main benefits of placing a package on GNU ELPA is that this archive is configured by default, and there is a realistic path for it to be shipped with Emacs in the future.

With GNU ELPA, one interesting recent development is that there is effort underway for automatically installing necessary support packages. The hope is that this will be part of Emacs 28.1. When finished, for apparmor-mode this could mean that any Emacs user that opened an apparmor file, out of the box, will be offered to install your package. That will only be possible for GNU ELPA packages, however, as Emacs itself for legal reasons cannot depend on any packages that do not have their copyright assignment to the FSF. See ongoing development at: https://elpa.gnu.org/packages/gnu-elpa.html

It is obviously your prerogative to do as you prefer. I am a happy user in any case, and MELPA is not a bad choice.

**Comment by alexmurray** [comment]
Since this has now moved to the upstream apparmor project at https://gitlab.com/apparmor/apparmor I am closing this issue.
